const Professions = [
"Physician",
"Teacher",
"Engineer",
"Lawyer",
"Pharmacist",
"Veterinarian",
"Accountant",
"Technician",
"Architect",
"Psychologist",
"Dentist",
"Scientist",
"Labourer",
"Software Developer",
"Electrician",
"Registered nurse",
"Dietitian",
"Occupational Therapist",
"Firefighter",
"Plumber",
"Secretary",
"Police officer",
"Librarian",
"Consultant",
"Chef",
"Actor",
"Mechanic",
"Farmer",
"Midwife",
"Hairdresser",
"Aviator",
"Technologist",
"Designer",
"Artist",
"Dental hygienist",
"Biomedical Engineer",
"Cook",
"Surgeon",
"Physiotherapist",
"Health professional",
"Economist",
"Radiographer",
"Operator",
"Statistician",
"Paramedic",
"Actuary",
"Civil engineer",
"Respiratory therapist",
"Air traffic controller",
"Waiting staff",
"Dental assistant"
]

export default Professions;
